# Generated by Django 3.2.19 on 2023-06-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_like_unique_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата создания будет автоматически установлена в текущую дату при создании', null=True, verbose_name='Дата создания'),
        ),
    ]
